name: 'Build pnpm dist branch'
description: 'Build npm package and push to dist branch'

inputs:
  source_ref:
    description: 'Source ref to build from (defaults to repository default branch)'
    required: false
    default: ''
  node_version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  pnpm_version:
    description: 'pnpm version to use'
    required: false
    default: '10'
  build_command:
    description: 'Build command to run'
    required: false
    default: 'pnpm run build'
  dist_branch:
    description: 'Name of dist branch'
    required: false
    default: 'dist'
  build_dir:
    description: 'Directory created by build command (moved to root on dist branch)'
    required: false
    default: 'dist'
  source_dirs:
    description: 'Comma-separated list of directories to include (e.g., "src,types"). If set, these are preserved as-is instead of moving dist/* to root.'
    required: false
    default: ''
  version_suffix:
    description: 'Add version suffix with git SHA (e.g., 0.1.0-dist.abc1234). Set to "false" to disable.'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.source_ref || github.event.repository.default_branch }}
        fetch-depth: 0

    - name: Get package and source info
      id: info
      shell: bash
      run: |
        echo "source_sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "pkg_name=$(jq -r .name package.json)" >> $GITHUB_OUTPUT

    - uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm_version }}

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Build
      shell: bash
      run: ${{ inputs.build_command }}

    - name: Build and commit to dist branch
      shell: bash
      env:
        DIST_BRANCH: ${{ inputs.dist_branch || 'dist' }}
        BUILD_DIR: ${{ inputs.build_dir }}
        SOURCE_DIRS: ${{ inputs.source_dirs }}
        VERSION_SUFFIX: ${{ inputs.version_suffix }}
      run: ${{ github.action_path }}/scripts/build-dist.sh ${{ steps.info.outputs.source_sha }}

    - name: Get dist SHA
      id: dist
      shell: bash
      run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Push dist branch
      shell: bash
      run: git push origin ${{ inputs.dist_branch || 'dist' }} --force-with-lease

    - name: Output dist branch info
      shell: bash
      run: |
        PKG_NAME="${{ steps.info.outputs.pkg_name }}"
        DIST_BRANCH="${{ inputs.dist_branch || 'dist' }}"
        DIST_SHA="${{ steps.dist.outputs.sha }}"
        SOURCE_SHA="${{ steps.info.outputs.source_sha }}"
        REPO="${{ github.repository }}"

        echo ""
        echo "=========================================="
        echo "✅ Dist branch updated successfully!"
        echo "=========================================="
        echo ""
        echo "📦 Package: ${PKG_NAME}"
        echo "🌿 Branch: ${DIST_BRANCH}"
        echo "🔗 Dist SHA: ${DIST_SHA}"
        echo "📝 Source SHA: ${SOURCE_SHA}"
        echo ""
        echo "To use this version:"
        echo "  pnpm add github:${REPO}#${DIST_SHA}"
        echo ""
        echo "Or with pnpm-dep-source:"
        echo "  pds github <dep> ${DIST_BRANCH}"
        echo ""

        # Add annotations that appear on Summary page
        echo "::notice title=🌿 Dist Branch Updated::${DIST_BRANCH} @ ${DIST_SHA:0:7}"
        echo "::notice title=📦 Install Command::pnpm add github:${REPO}#${DIST_SHA}"
